import {
  OfficeMapData,
  Department,
  AIEmployee,
  AITask,
  AIActivityLog,
  AIKnowledgeDoc,
  AIKpi,
} from '@/src/types';

export const DEFAULT_WORKSPACE_ID = 'acme_corp';

export const INITIAL_OFFICE_MAP: OfficeMapData = {
  id: 'hq_main_floor',
  workspaceId: DEFAULT_WORKSPACE_ID,
  name: 'Acme Global HQ — Floor 1',
  width: 36,
  height: 24,
  tileSize: 32,
  rooms: [
    {
      id: 'room_lobby',
      name: 'Main Lobby & Reception',
      category: 'LOBBY',
      x: 1,
      y: 1,
      width: 11,
      height: 7,
      floorColor: '#1e293b',
    },
    {
      id: 'room_meeting',
      name: 'Boardroom Alpha (Meeting)',
      category: 'MEETING_ROOM',
      x: 13,
      y: 1,
      width: 11,
      height: 7,
      floorColor: '#172554',
    },
    {
      id: 'room_lounge',
      name: 'Coffee Lounge & Pantry',
      category: 'LOUNGE',
      x: 25,
      y: 1,
      width: 10,
      height: 7,
      floorColor: '#312e81',
    },
    {
      id: 'room_marketing',
      name: 'Marketing & Growth Wing',
      category: 'WORKSPACE',
      x: 1,
      y: 9,
      width: 11,
      height: 14,
      floorColor: '#0f172a',
      departmentId: 'dept_marketing',
    },
    {
      id: 'room_engineering',
      name: 'Engineering & AI Core Lab',
      category: 'WORKSPACE',
      x: 13,
      y: 9,
      width: 11,
      height: 14,
      floorColor: '#091926',
      departmentId: 'dept_engineering',
    },
    {
      id: 'room_finance',
      name: 'Finance & Executive Suite',
      category: 'PRIVATE_OFFICE',
      x: 25,
      y: 9,
      width: 10,
      height: 14,
      floorColor: '#111827',
      departmentId: 'dept_finance',
    },
  ],
  portals: [
    {
      id: 'portal_lobby_to_boardroom',
      label: 'Teleport to Boardroom',
      sourceX: 11,
      sourceY: 2,
      destinationX: 15,
      destinationY: 4,
      destinationRoomId: 'room_meeting',
    },
    {
      id: 'portal_lounge_to_eng',
      label: 'Quick Drop to Engineering',
      sourceX: 33,
      sourceY: 2,
      destinationX: 18,
      destinationY: 14,
      destinationRoomId: 'room_engineering',
    },
  ],
  objects: [
    // Reception & Lobby
    {
      id: 'obj_reception_desk',
      type: 'desk',
      label: 'Reception Concierge Desk',
      x: 5,
      y: 3,
      width: 3,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_DOCS',
      roomId: 'room_lobby',
    },
    {
      id: 'obj_lobby_plant_1',
      type: 'plant',
      label: 'Monstera Office Plant',
      x: 2,
      y: 2,
      width: 1,
      height: 1,
      collidable: true,
      interactive: false,
      roomId: 'room_lobby',
    },
    {
      id: 'obj_lobby_tv',
      type: 'tv',
      label: 'Company KPI Broadcast Screen',
      x: 8,
      y: 1,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'VIEW_METRICS',
      roomId: 'room_lobby',
    },
    // Boardroom Alpha (Meeting Room)
    {
      id: 'obj_boardroom_table',
      type: 'meeting_table',
      label: 'Boardroom Conference Table (Join Call)',
      x: 16,
      y: 3,
      width: 5,
      height: 2,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_MEETING',
      roomId: 'room_meeting',
    },
    {
      id: 'obj_boardroom_wb',
      type: 'whiteboard',
      label: 'Strategy Collaborative Whiteboard',
      x: 14,
      y: 1,
      width: 3,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_WHITEBOARD',
      roomId: 'room_meeting',
    },
    // Lounge & Pantry
    {
      id: 'obj_coffee_machine',
      type: 'coffee_machine',
      label: 'Espresso Barista Station',
      x: 27,
      y: 2,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'BREW_COFFEE',
      roomId: 'room_lounge',
    },
    {
      id: 'obj_lounge_sofa',
      type: 'sofa',
      label: 'Relaxation Lounge Sofa',
      x: 30,
      y: 4,
      width: 3,
      height: 1,
      collidable: true,
      interactive: false,
      roomId: 'room_lounge',
    },
    // Marketing Department Desks
    {
      id: 'obj_mkt_desk_1',
      type: 'computer',
      label: 'Sarah AI Workstation (Marketing Strategy)',
      x: 3,
      y: 12,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_marketing',
    },
    {
      id: 'obj_mkt_desk_2',
      type: 'computer',
      label: 'Alex AI Workstation (Copywriting)',
      x: 7,
      y: 12,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_marketing',
    },
    {
      id: 'obj_mkt_desk_3',
      type: 'desk',
      label: 'Andi Supervisor Desk (Marketing Lead)',
      x: 5,
      y: 17,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_marketing',
    },
    {
      id: 'obj_mkt_bookshelf',
      type: 'bookshelf',
      label: 'Brand Guidelines & SEO Knowledge Vault',
      x: 2,
      y: 20,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_DOCS',
      roomId: 'room_marketing',
    },
    // Engineering Department Desks
    {
      id: 'obj_eng_desk_1',
      type: 'computer',
      label: 'Codey AI Workstation (Principal Architect)',
      x: 15,
      y: 12,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_engineering',
    },
    {
      id: 'obj_eng_desk_2',
      type: 'computer',
      label: 'Nova AI Workstation (DevSecOps & QA)',
      x: 19,
      y: 12,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_engineering',
    },
    {
      id: 'obj_eng_desk_3',
      type: 'desk',
      label: 'Budi Supervisor Desk (VP Engineering)',
      x: 17,
      y: 17,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_engineering',
    },
    {
      id: 'obj_eng_servers',
      type: 'server_rack',
      label: 'NVIDIA DGX H100 AI Inference Cluster',
      x: 14,
      y: 20,
      width: 3,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'VIEW_METRICS',
      roomId: 'room_engineering',
    },
    // Finance Department Desks
    {
      id: 'obj_fin_desk_1',
      type: 'computer',
      label: 'Fin AI Workstation (FP&A & Risk Audit)',
      x: 27,
      y: 12,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_finance',
    },
    {
      id: 'obj_fin_desk_2',
      type: 'computer',
      label: 'Maya AI Workstation (Market & Revenue Intel)',
      x: 31,
      y: 12,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_finance',
    },
    {
      id: 'obj_fin_desk_3',
      type: 'desk',
      label: 'Siti Supervisor Desk (Finance Controller)',
      x: 29,
      y: 17,
      width: 2,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_AI_CENTER',
      roomId: 'room_finance',
    },
    {
      id: 'obj_fin_printer',
      type: 'printer',
      label: 'Executive Ledger & Audit Printer',
      x: 32,
      y: 20,
      width: 1,
      height: 1,
      collidable: true,
      interactive: true,
      actionType: 'OPEN_DOCS',
      roomId: 'room_finance',
    },
    {
      id: 'obj_fin_plant',
      type: 'plant',
      label: 'Executive Bamboo Palm',
      x: 26,
      y: 20,
      width: 1,
      height: 1,
      collidable: true,
      interactive: false,
      roomId: 'room_finance',
    },
  ],
};

export const INITIAL_DEPARTMENTS: Omit<Department, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'dept_marketing',
    workspaceId: DEFAULT_WORKSPACE_ID,
    name: 'Marketing',
    supervisorId: 'sup_andi',
    supervisorName: 'Andi Pratama',
    goals:
      'Drive 50+ qualified enterprise leads/month, maintain 92%+ brand compliance, and optimize Q4 omnichannel conversion.',
    monthlyBudget: 150,
    spentBudget: 34.6,
    paused: false,
  },
  {
    id: 'dept_engineering',
    workspaceId: DEFAULT_WORKSPACE_ID,
    name: 'Engineering',
    supervisorId: 'sup_budi',
    supervisorName: 'Budi Santoso',
    goals:
      'Maintain 99.95% realtime WebSocket uptime, zero critical security vulnerabilities, and ship autonomous agent pipelines.',
    monthlyBudget: 250,
    spentBudget: 62.4,
    paused: false,
  },
  {
    id: 'dept_finance',
    workspaceId: DEFAULT_WORKSPACE_ID,
    name: 'Finance',
    supervisorId: 'sup_siti',
    supervisorName: 'Siti Rahma',
    goals:
      'Audit all AI departmental token spend, forecast Q4 SaaS ARR, and enforce strict approval gates on financial transactions.',
    monthlyBudget: 120,
    spentBudget: 19.8,
    paused: false,
  },
];

export const INITIAL_AI_EMPLOYEES: Omit<AIEmployee, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'ai_sarah',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_marketing',
    supervisorId: 'sup_andi',
    name: 'Sarah',
    role: 'Marketing Strategist',
    avatarColor: '#10b981',
    personality: 'Analytical, data-driven, creative, and structured.',
    systemPrompt:
      'You are Sarah, Senior AI Marketing Strategist at Acme Corp reporting to Human Supervisor Andi Pratama. Focus on GTM strategy, competitor intelligence, SEO, and conversion funnels. Never launch external paid campaigns or email blasts without human supervisor approval.',
    restrictions:
      'Cannot publish external campaigns without approval. Cannot spend budget directly. Cannot modify company security settings.',
    modelProvider: 'NINEROUTER',
    modelName: 'openrouter/auto',
    temperature: 0.7,
    autonomyLevel: 2,
    status: 'WORKING',
    dailyBudget: 15,
    monthlyBudget: 60,
    spentToday: 3.4,
    spentMonth: 18.2,
    performanceScore: 94,
    tasksCompleted: 127,
    tasksPending: 3,
    x: 4 * 32,
    y: 13.5 * 32,
    roomId: 'room_marketing',
  },
  {
    id: 'ai_alex',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_marketing',
    supervisorId: 'sup_andi',
    name: 'Alex',
    role: 'Lead Copywriter & Content AI',
    avatarColor: '#06b6d4',
    personality: 'Articulate, persuasive, brand-conscious, and concise.',
    systemPrompt:
      'You are Alex, Lead Copywriter AI in the Marketing Department supervised by Andi Pratama. Craft high-converting landing copy, technical whitepapers, and product announcements following Brand Guidelines.',
    restrictions:
      'Cannot publish directly to production CMS or send customer emails without approval.',
    modelProvider: 'NINEROUTER',
    modelName: 'openrouter/auto',
    temperature: 0.8,
    autonomyLevel: 2,
    status: 'THINKING',
    dailyBudget: 10,
    monthlyBudget: 45,
    spentToday: 1.8,
    spentMonth: 11.4,
    performanceScore: 91,
    tasksCompleted: 89,
    tasksPending: 2,
    x: 8 * 32,
    y: 13.5 * 32,
    roomId: 'room_marketing',
  },
  {
    id: 'ai_codey',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_engineering',
    supervisorId: 'sup_budi',
    name: 'Codey',
    role: 'Principal Systems Architect AI',
    avatarColor: '#3b82f6',
    personality: 'Rigorous, security-first, pragmatic, and detail-oriented.',
    systemPrompt:
      'You are Codey, Principal Systems Architect AI in Engineering supervised by Budi Santoso. Design clean TypeScript architectures, optimize WebSocket latency, and audit database queries.',
    restrictions:
      'Cannot execute destructive database migrations or alter production IAM permissions.',
    modelProvider: 'NINEROUTER',
    modelName: 'openrouter/auto',
    temperature: 0.3,
    autonomyLevel: 3,
    status: 'WORKING',
    dailyBudget: 25,
    monthlyBudget: 120,
    spentToday: 6.2,
    spentMonth: 38.9,
    performanceScore: 96,
    tasksCompleted: 214,
    tasksPending: 4,
    x: 16 * 32,
    y: 13.5 * 32,
    roomId: 'room_engineering',
  },
  {
    id: 'ai_nova',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_engineering',
    supervisorId: 'sup_budi',
    name: 'Nova',
    role: 'DevSecOps & QA Automation AI',
    avatarColor: '#8b5cf6',
    personality: 'Vigilant, methodical, zero-trust security mindset.',
    systemPrompt:
      'You are Nova, DevSecOps & QA AI in Engineering supervised by Budi Santoso. Continuously verify RBAC boundaries, inspect API payloads, and write E2E test suites.',
    restrictions:
      'Cannot disable security rules, delete audit logs, or modify production secrets.',
    modelProvider: 'NINEROUTER',
    modelName: 'openrouter/auto',
    temperature: 0.2,
    autonomyLevel: 2,
    status: 'PROCESSING',
    dailyBudget: 20,
    monthlyBudget: 90,
    spentToday: 4.1,
    spentMonth: 23.5,
    performanceScore: 95,
    tasksCompleted: 163,
    tasksPending: 1,
    x: 20 * 32,
    y: 13.5 * 32,
    roomId: 'room_engineering',
  },
  {
    id: 'ai_fin',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_finance',
    supervisorId: 'sup_siti',
    name: 'Fin',
    role: 'FP&A & Cost Governance AI',
    avatarColor: '#f59e0b',
    personality: 'Precise, conservative, transparent with numbers and risk.',
    systemPrompt:
      'You are Fin, Financial Planning & Governance AI in Finance supervised by Siti Rahma. Track token costs, department burn rates, ROI metrics, and flag high-risk expenditures.',
    restrictions:
      'Cannot authorize wire transfers, alter department budgets, or approve invoices without human supervisor signature.',
    modelProvider: 'NINEROUTER',
    modelName: 'openrouter/auto',
    temperature: 0.2,
    autonomyLevel: 2,
    status: 'WAITING_APPROVAL',
    dailyBudget: 12,
    monthlyBudget: 60,
    spentToday: 2.1,
    spentMonth: 12.6,
    performanceScore: 93,
    tasksCompleted: 108,
    tasksPending: 2,
    x: 28 * 32,
    y: 13.5 * 32,
    roomId: 'room_finance',
  },
  {
    id: 'ai_maya',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_finance',
    supervisorId: 'sup_siti',
    name: 'Maya',
    role: 'Market & Revenue Intelligence AI',
    avatarColor: '#ec4899',
    personality: 'Inquisitive, synthesizer of macro trends and unit economics.',
    systemPrompt:
      'You are Maya, Market & Revenue Intelligence AI collaborating across Finance and Marketing, supervised by Siti Rahma. Synthesize competitor pricing, CAC/LTV ratios, and expansion opportunities.',
    restrictions:
      'Cannot share proprietary financial models externally or execute paid data purchases.',
    modelProvider: 'NINEROUTER',
    modelName: 'openrouter/auto',
    temperature: 0.5,
    autonomyLevel: 2,
    status: 'WORKING',
    dailyBudget: 12,
    monthlyBudget: 50,
    spentToday: 1.4,
    spentMonth: 7.2,
    performanceScore: 92,
    tasksCompleted: 76,
    tasksPending: 2,
    x: 32 * 32,
    y: 13.5 * 32,
    roomId: 'room_finance',
  },
];

export const INITIAL_AI_TASKS: Omit<AITask, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'task_q4_campaign_blast',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_marketing',
    aiEmployeeId: 'ai_sarah',
    aiEmployeeName: 'Sarah',
    creatorId: 'sup_andi',
    title: 'Send Q4 Enterprise Product Launch Campaign to 12,500 Customers',
    description:
      'Execute segmented email & enterprise outbound sequence for Q4 AI Workforce Platform launch across APAC and EMEA cohorts.',
    priority: 'HIGH',
    status: 'REVIEW',
    riskLevel: 'HIGH',
    requiresApproval: true,
    estimatedCost: 42.0,
    outputReport:
      '### Campaign Execution Plan (Awaiting Human-in-the-Loop Approval)\n- **Target Cohort**: 12,500 verified enterprise decision-makers\n- **Projected Open Rate**: 38.4%\n- **Projected Pipeline Contribution**: $185,000 ARR\n- **Governance Flag**: External communication to >1,000 recipients triggers mandatory Supervisor Approval.',
    deadline: 'Friday 17:00',
  },
  {
    id: 'task_competitor_analysis',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_marketing',
    aiEmployeeId: 'ai_alex',
    aiEmployeeName: 'Alex',
    creatorId: 'sup_andi',
    title: 'Create Q4 Competitor Positioning Matrix & Landing Page Copy',
    description:
      'Benchmark virtual office & AI agent platforms and draft high-conversion hero and enterprise governance messaging.',
    priority: 'MEDIUM',
    status: 'WORKING',
    riskLevel: 'LOW',
    requiresApproval: false,
    estimatedCost: 2.4,
    outputReport:
      'Drafting messaging pillars comparing static video tools against spatial 2D human + AI collaboration.',
    deadline: 'Thursday 15:00',
  },
  {
    id: 'task_ws_scaling_audit',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_engineering',
    aiEmployeeId: 'ai_codey',
    aiEmployeeName: 'Codey',
    creatorId: 'sup_budi',
    title: 'Optimize Spatial Proximity Audio & Position Interpolation',
    description:
      'Verify Euclidean distance attenuation curve and 150ms movement throttling to eliminate DB write spikes.',
    priority: 'HIGH',
    status: 'COMPLETED',
    riskLevel: 'LOW',
    requiresApproval: false,
    estimatedCost: 4.8,
    outputReport:
      '### Architecture Verification Complete\n- Movement packets throttled to 180ms intervals.\n- Linear interpolation (LERP) active at 60fps in Phaser scene.\n- Zero per-frame database writes confirmed.',
    deadline: 'Completed',
  },
  {
    id: 'task_cloud_budget_reallocation',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_finance',
    aiEmployeeId: 'ai_fin',
    aiEmployeeName: 'Fin',
    creatorId: 'sup_siti',
    title: 'Approve Q4 NVIDIA Inference Reserve Allocation ($1,200)',
    description:
      'Reserve dedicated throughput capacity for Llama-3.1-70B-Instruct across Marketing, Engineering, and Finance agents.',
    priority: 'CRITICAL',
    status: 'REVIEW',
    riskLevel: 'CRITICAL',
    requiresApproval: true,
    estimatedCost: 58.0,
    outputReport:
      '### Financial Risk & ROI Assessment\n- **Requested Commitment**: $1,200/month reserved inference tier\n- **Unit Cost Reduction**: -31% per 1M tokens\n- **Governance Policy**: Financial transactions require explicit Human Supervisor sign-off.',
    deadline: 'Today 18:00',
  },
];

export const INITIAL_KNOWLEDGE_DOCS: Omit<AIKnowledgeDoc, 'createdAt'>[] = [
  {
    id: 'doc_mkt_strategy',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_marketing',
    title: 'Marketing Strategy & Brand Guidelines Q4.pdf',
    category: 'Brand & GTM',
    content:
      'Core positioning: NexusOS is the enterprise virtual headquarters where human supervisors orchestrate specialized AI employees in real time. Tone of voice: authoritative, transparent, human-centric. Outbound policy: Any campaign exceeding 500 recipients or $25 ad spend requires Human Supervisor approval.',
    authorId: 'sup_andi',
  },
  {
    id: 'doc_eng_security',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_engineering',
    title: 'Zero-Trust AI Agent Architecture & RBAC Spec.pdf',
    category: 'Security & Architecture',
    content:
      'All LLM calls execute server-side via NVIDIA NIM (`integrate.api.nvidia.com/v1`) or Google Gemini (`@google/genai`). AI agents never receive raw database credentials, cannot escalate their own autonomy level, and cannot mutate audit logs.',
    authorId: 'sup_budi',
  },
  {
    id: 'doc_fin_policy',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_finance',
    title: 'Corporate AI Token Budget & Procurement Policy.pdf',
    category: 'Finance & Compliance',
    content:
      'Each AI employee operates within strict Daily and Monthly USD token ceilings. If an AI employee exceeds 100% of its daily budget, its status automatically transitions to PAUSED until reviewed by the Department Supervisor.',
    authorId: 'sup_siti',
  },
];

export const INITIAL_KPIS: Omit<AIKpi, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'kpi_mkt_leads',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_marketing',
    aiEmployeeId: 'ai_sarah',
    title: 'Qualified Enterprise Leads Generated / Month',
    targetValue: 50,
    currentValue: 39,
    unit: 'leads',
    creatorId: 'sup_andi',
  },
  {
    id: 'kpi_eng_latency',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_engineering',
    aiEmployeeId: 'ai_codey',
    title: 'Automated Architecture & PR Reviews Completed',
    targetValue: 100,
    currentValue: 94,
    unit: 'reviews',
    creatorId: 'sup_budi',
  },
  {
    id: 'kpi_fin_audit',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_finance',
    aiEmployeeId: 'ai_fin',
    title: 'Zero-Discrepancy Token Spend Audits',
    targetValue: 30,
    currentValue: 28,
    unit: 'audits',
    creatorId: 'sup_siti',
  },
];

export const INITIAL_ACTIVITY_LOGS: Omit<AIActivityLog, 'createdAt'>[] = [
  {
    id: 'log_init_1',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_marketing',
    aiEmployeeId: 'ai_sarah',
    aiEmployeeName: 'Sarah',
    actorId: 'sup_andi',
    action: 'Requested Human Approval: Q4 Enterprise Launch Campaign',
    details:
      'Target: 12,500 customers. Risk Level: HIGH. Estimated Cost: $42.00. Paused execution pending Andi Pratama review.',
    status: 'PENDING_APPROVAL',
    riskLevel: 'HIGH',
    costIncurred: 0.45,
  },
  {
    id: 'log_init_2',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_engineering',
    aiEmployeeId: 'ai_codey',
    aiEmployeeName: 'Codey',
    actorId: 'sup_budi',
    action: 'Executed Tool: verifyRealtimeInterpolation',
    details:
      'Validated Phaser 2D arcade physics collision boundaries and 180ms presence synchronization.',
    status: 'SUCCESS',
    riskLevel: 'LOW',
    costIncurred: 0.32,
  },
  {
    id: 'log_init_3',
    workspaceId: DEFAULT_WORKSPACE_ID,
    departmentId: 'dept_finance',
    aiEmployeeId: 'ai_fin',
    aiEmployeeName: 'Fin',
    actorId: 'sup_siti',
    action: 'Requested Critical Approval: NVIDIA Inference Reserve ($1,200)',
    details:
      'Flagged CRITICAL financial commitment for human controller sign-off.',
    status: 'PENDING_APPROVAL',
    riskLevel: 'CRITICAL',
    costIncurred: 0.28,
  },
];
